language: python
python:
  - "3.6"

notifications:
  slack: privateuser-workspace:5hybgvvnXJOVAuc01WiKfrmX

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"